create a numpy array

In [2]:
import numpy as np

The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not.

In [4]:
list1=[1,2,3,4,5]
arr=np.array(list1)
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

type of the Array

In [5]:
list1=[1,2,3,4,5]
arr=np.array(list1)
print(type(arr))

<class 'numpy.ndarray'>


can't do operations on every item of list
but array can do it on array

In [3]:
list1=[1,2,3,4,5]
list2=[5,4,3,2,1]
arr=np.array(list1)
print(list1+2) #cant add int to list type mismatch error
print(list1+list2)#adding 2 list will give combined items from first and second


[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]


In [4]:
list1=[1,2,3,4,5]
list2=[5,4,3,2,1]
arr=np.array(list1)
arr2=np.array(list2)
print(arr+2) #add 2 with every items
print(arr+arr2)# add first array elements with sec array and give resultant sum

[3 4 5 6 7]
[6 6 6 6 6]


once a numpy array is created, you cannot increase its size. To do so, you will have to create a new array. But such a behavior of extending the size is natural in a list.


the most commonly used numpy dtypes are: 'float', 'int', 'bool', 'str' and 'object'.
To control the memory allocations you may choose to use one of ‘float32’, ‘float64’, ‘int8’, ‘int16’ or ‘int32’.
if you want to hold characters and numbers in the same array, 

In [7]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr=np.array(list2)
print("Array")
print(arr)
arr_f=np.array(list2,dtype='float')
print("Float")
print(arr_f)
arr_i=arr_f.astype('int')
print("Int")
print(arr_i)
arr_s=arr_i.astype('str')
print("String")
print(arr_s,"\n")
arr_b=np.array([0, 11, 10], dtype='bool')
print("Boolean")
print(arr_b)
arr_obj=np.array([1,'a'],dtype='object')
print("Object")
print(arr_obj)

Array
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Float
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Int
[[0 1 2]
 [3 4 5]
 [6 7 8]]
String
[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']] 

Boolean
[False  True  True]
Object
[1 'a']


How to inspect the size and shape of a numpy array

In [7]:
list2 = [[[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]]
arr2 = np.array(list2, dtype='int8')
arr2
# shape
print("Shape")
arr_shape=arr2.shape
print(arr_shape,"\n")
# dtype
print("Dtype")
arr_type=arr2.dtype
print(arr_type,"\n")
# size
print("Size")
arr_size=arr2.size
print(arr_size,"\n")
print("Dimensional")
arr_dim=arr2.ndim
print(arr_dim)


Shape
(1, 3, 4) 

Dtype
int8 

Size
12 

Dimensional
3


How to extract specific items from an array
numpy arrays can optionally accept as many parameters in the square brackets as there is number of dimensions.
list doesn't have this property it will throw error

In [23]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='int')
arr2
print("Extract 1st 2 rows and cols" )
new_arr=arr2[:2,:2]
print(new_arr)
print(list2[:2, :2])

Extract 1st 2 rows and cols
[[1 2]
 [5 6]]


TypeError: list indices must be integers or slices, not tuple

In [8]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='int')
print(arr2)
print("Extract 1st 2 rows and cols" )
new_arr=arr2[:4:2,:4:2]#[start:stop:step]
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Extract 1st 2 rows and cols
[[ 1  3]
 [ 9 11]]


numpy arrays support boolean indexing.
A boolean index array is of the same shape as the array-to-be-filtered and it contains only True and False values. The values corresponding to True positions are retained in the output.


In [27]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='int')
new_arr=arr2 %2==0
print("Original Array")
print(arr2,"\n")
print("Boolean Array")
print(new_arr,"\n")
new_arr_val=arr2[new_arr]
print("Array Values with Condition")
print(new_arr_val)

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Boolean Array
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]] 

Array Values with Condition
[ 2  4  6  8 10 12]


# Need Clarification
How to reverse the rows and the whole array
you need to do for all the axes (dimensions) if you want a complete reversal.


In [32]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='int')
print("Original Array")
print(arr2,"\n")
#Reverse only the row positions
print("Reverse only the row positions")
rev_arr=arr2[::-1,]
print(rev_arr,"\n")

print("Reverse the row and column positions")
sec_rev_arr=arr2[::-1,::-1]
print(sec_rev_arr,"\n")

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Reverse only the row positions
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]] 

Reverse the row and column positions
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]] 



How to represent missing values and infinite
np.nan : Missing Vlaue (not a number)
np.inf : infinite
Replace nan and inf with -1. Don't use arr2 == np.nan
np.isnan(array) | np.isinf(array)

In [35]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='float')
print("Original Array")
print(arr2,"\n")
arr2[1,1]=np.nan
arr2[1,2]=np.inf
print("missing values and infinite")
print(arr2)
#Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool=np.isnan(arr2)|np.isinf(arr2)
arr2[missing_bool]=-1
print("Replace nan and inf with -1")
print(arr2)

Original Array
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

missing values and infinite
[[ 1.  2.  3.  4.]
 [ 5. nan inf  8.]
 [ 9. 10. 11. 12.]]
Replace nan and inf with -1
[[ 1.  2.  3.  4.]
 [ 5. -1. -1.  8.]
 [ 9. 10. 11. 12.]]


How to compute mean, min, max on the ndarray
compute the minimum values row wise or column wise, use the np.amin version .
Cumulative Sum : Adding Previous sum to the next num

In [43]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='float')
print("Original Array")
print(arr2,"\n")
print("Mean value")
print(arr2.mean(),"\n")
print("Min value")
print(arr2.min(),"\n")
print("Max value")
print(arr2.max(),"\n")
print("Row wise  min")
row_min=np.amin(arr2,axis=1)
print(row_min,"\n")
print("Col wise  min")
col_min=np.amin(arr2,axis=0)
print(col_min,"\n")
print("Cumulative Sum")
cum_sum=np.cumsum(arr2)
print(cum_sum)

Original Array
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

Mean value
6.5 

Min value
1.0 

Max value
12.0 

Row wise  min
[1. 5. 9.] 

Col wise  min
[1. 2. 3. 4.] 

Cumulative Sum
[ 1.  3.  6. 10. 15. 21. 28. 36. 45. 55. 66. 78.]


How to create a new array from an existing array
If you just assign a portion of an array to another array, the new array you just created actually refers to the parent array in memory.

That means, if you make any changes to the new array, it will reflect in the parent array as well.

So to avoid disturbing the parent array, you need to make a copy of it 

In [47]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='float')
print("Original Array")
print(arr2,"\n")
arr2a=arr2[:2,:2]
print("New Array")
print(arr2a,"\n")
arr2a[:1,:1]=100
print("Updated Array")
print(arr2a)
print("Original After Updated")
print(arr2)

Original Array
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

New Array
[[1. 2.]
 [5. 6.]] 

Updated Array
[[100.   2.]
 [  5.   6.]]
Original After Updated
[[100.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]]


Copy portion of arr2 to arr2b

In [53]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='float')
print("Original Array")
print(arr2,"\n")

print("Copied Array")
arr2b=arr2[:2,:2].copy()
print(arr2b,"\n")
arr2b[:1,:1]=101
print("Updated Array")
print(arr2b,"\n")
print("Original After Updated")
print(arr2)

Original Array
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

Copied Array
[[1. 2.]
 [5. 6.]] 

Updated Array
[[101.   2.]
 [  5.   6.]] 

Original After Updated
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


Reshaping and Flattening Multidimensional arrays
Reshaping is changing the arrangement of items so that shape of the array changes while maintaining the same number of dimensions.
Flattening, however, will convert a multi-dimensional array to a flat 1d array. And not any other shape.


In [9]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='float')
print("Original Array")
print(arr2,"\n")
rs_one=arr2.reshape(4, 3)
print("One Shape Array")
print(rs_one,"\n")
rs_two=arr2.reshape(6, 2)
print("Two Shape Array")
print(rs_two,"\n")

Original Array
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

One Shape Array
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]] 

Two Shape Array
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]] 



2 popular ways to implement flattening : difference between flatten() and ravel()
flatten() : Flatten it to a 1d array.Changing the flattened array does not change parent
ravel() : the new array created using ravel is actually a reference to the parent array. So, any changes to the new array will affect the parent as well. But is memory efficient since it does not create a copy.


In [15]:
list2 = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2, dtype='float')
print("Original Array")
print(arr2,"\n")
new_arr=arr2.flatten();
new_arr[1]=20
print("Flatten array after changes value")
print(new_arr,"\n")
print("Original array after changes value")
print(arr2,"\n")
#RAVEL
rav_arr=arr2.ravel()
rav_arr[3]=50
print("Ravel array after changes value")
print(rav_arr,"\n")
print("Original array after changes value")
print(arr2,"\n")

Original Array
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

Flatten array after changes value
[ 1. 20.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.] 

Original array after changes value
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

Ravel array after changes value
[ 1.  2.  3. 50.  5.  6.  7.  8.  9. 10. 11. 12.] 

Original array after changes value
[[ 1.  2.  3. 50.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 



How to create sequences, repetitions and random numbers using numpy?
np.arange function comes handy to create customised number sequences as ndarray.


In [20]:
print(" Lower limit is 0 be default \n")
arr1=np.arange(5)
print("Arange to index \n")
print(arr1,"\n")

arr2=np.arange(5,25)
print("Arange from to index \n")
print(arr2,"\n")

arr3=np.arange(25,5,-1)
print("Arange decreasing order \n")
print(arr3,"\n")


 Lower limit is 0 be default 

Arange to index 

[0 1 2 3 4] 

Arange from to index 

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

Arange decreasing order 

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6] 



you want to create an array of exactly 10 numbers between 1 and 50, Can you compute what would be the step value?
use the np.linspace . It divides the values exactly to get the 10 outputs.

In [22]:
arr1=np.linspace(1,50,10,dtype="int")
print(arr1)

[ 1  6 11 17 22 28 33 39 44 50]


np.logspace which rises in a logarithmic scale.

In [28]:
print("Limit the number of digits after the decimal to 2")
prnt_op=np.set_printoptions(precision=2) 
print(prnt_op,"\n")
print("Start at 10^1 and end at 10^50","\n")
log_n=np.logspace(1,50,10,10)
print(log_n)

Limit the number of digits after the decimal to 2
None 

Start at 10^1 and end at 10^50 

[1.00e+01 2.78e+06 7.74e+11 2.15e+17 5.99e+22 1.67e+28 4.64e+33 1.29e+39
 3.59e+44 1.00e+50]


The np.zeros and np.ones functions lets you create arrays of desired shape where all the items are either 0’s or 1’s.

In [33]:
zeros_arr=np.zeros([5,3],dtype="int")
print("Zeroes")
print(zeros_arr,"\n")
print("Ones")
ones_arr=np.ones([3,6],dtype="int")
print(ones_arr,"\n")

Zeroes
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]] 

Ones
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 



How to create repeating sequences

In [37]:
list1=[1,2,3,4]
print("Tile Repeat whole of 'list1' n times")
tile_arr=np.tile(list1,3)
print(tile_arr,"\n")
print(" Repeat each element of 'list1' n times")
rep_arr=np.repeat(list1,3)
print(rep_arr)

Tile Repeat whole of 'list1' n times
[1 2 3 4 1 2 3 4 1 2 3 4] 

 Repeat each element of 'list1' n times
[1 1 1 2 2 2 3 3 3 4 4 4]


# Need clarification

How to generate random numbers?
The random module provides nice functions to generate random numbers (and also statistical distributions) of any given shape.

In [50]:
print("Random numbers between [0,1) of shape 2,2","\n")
arr_one=np.random.rand(2,2)
print(arr_one,"\n")
print("Normal distribution with mean=0 and variance=1 of shape 2,2","\n")
arr_two=np.random.randn(2,2)
print(arr_two)
print("\n Random integers between [0, 10) of shape 2,2 \n")
arr_three=np.random.randint(0, 5, size=[2,2])
print(arr_three,"\n")
print("One random number between [0,1) \n")
arr_four=np.random.random()
print(arr_four,"\n")
print("Pick n items from a given list, with equal probability \n")
arr_five=np.random.choice(['a', 'e', 'i', 'o', 'u'], size=15)
print(arr_five,"\n")
print("Pick n items from a given list with a predefined probability 'p' \n")
arr_six=np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1])
print(arr_six,"\n")

Random numbers between [0,1) of shape 2,2 

[[0.92 0.43]
 [0.38 0.42]] 

Normal distribution with mean=0 and variance=1 of shape 2,2 

[[-1.35 -0.61]
 [-0.99 -0.38]]

 Random integers between [0, 10) of shape 2,2 

[[4 3]
 [4 0]] 

One random number between [0,1) 

0.5660550902530471 

Pick n items from a given list, with equal probability 

['a' 'o' 'o' 'u' 'o' 'a' 'i' 'o' 'e' 'o' 'u' 'e' 'a' 'i' 'e'] 

Pick n items from a given list with a predefined probability 'p' 

['a' 'a' 'o' 'e' 'i' 'o' 'o' 'a' 'o' 'a'] 



everytime you run any of the above functions, you get a different set of random numbers.
you want to repeat the same set of random numbers every time, you need to set the seed or the random state. 
Once np.random.RandomState is created, all the functions of the np.random module becomes available to the created randomstate object.

In [56]:
rn = np.random.RandomState(100)
rand_num=rn.rand(2,2)
print(rand_num)
print("\n # Set the random seed \n")
np.random.seed(100)
rand_seed=np.random.rand(2,2)
print(rand_seed)

[[0.54 0.28]
 [0.42 0.84]]

 # Set the random seed 

[[0.54 0.28]
 [0.42 0.84]]


How to get the unique items and the counts?
The np.unique method can be used to get the unique items.
If you want the repetition counts of each item, set the return_counts parameter to True.
it create ascending order of unique items and gives the count

In [2]:
print("Create random integers of size 10 between [0,10) \n")
np.random.seed(100)
arr_rand= np.random.randint(0, 10, size=10)
print(arr_rand,"\n")
print("Get the unique items and their counts \n")
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : \n ", uniqs,"\n")
print("Counts       : \n", counts)
print("\n Only Unique Items")
unq=np.unique(arr_rand)
print(unq,"\n")

Create random integers of size 10 between [0,10) 

[8 8 3 7 7 0 4 2 5 2] 

Get the unique items and their counts 

Unique items : 
  [0 2 3 4 5 7 8] 

Counts       : 
 [1 2 1 1 1 2 2]

 Only Unique Items
[0 2 3 4 5 7 8] 

